=== elisacoello/SWII-/Recetario/recursos/DTD.dtd
<!ELEMENT recetario (receta*)>
<!ELEMENT receta (nombreReceta,ingredientes, instrucciones)>
<!ELEMENT nombreReceta (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombreIngrediente, cantidad)>
<!ELEMENT instrucciones (#PCDATA)>
<!ELEMENT nombreIngrediente (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST receta tipo CDATA #REQUIRED>
<!ATTLIST receta dificultad CDATA #IMPLIED>

=== elisacoello/SWII-/Recetario/recursos/Recetariobaby.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE recetario SYSTEM "DTD.dtd">
<recetario>
    <receta dificultad="facil" tipo="mediterranea">
        <nombreReceta>Ensalada de maiz</nombreReceta>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>Maiz</nombreIngrediente>
                <cantidad>0</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>Cocinar el maiz</instrucciones>
    </receta>
</recetario>

=== elisacoello/SWII-/Recetario/recursos/recetario_para_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetario SYSTEM "DTD.dtd">
<recetario>
    <receta dificultad="fácil" tipo="mediterranea">
        <nombreReceta>Ensalada de maiz</nombreReceta>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>Maizz</nombreIngrediente>
                <cantidad>0</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>Cocinar el maiz</instrucciones>
    </receta>
    <receta dificultad="media" tipo="Arabe">
        <nombreReceta>Ensalada de puerro</nombreReceta>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>puerro</nombreIngrediente>
                <cantidad>2</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>Cocinar el puerro</instrucciones>
    </receta>
    <receta dificultad="" tipo="fácil arabe">
        <nombreReceta>cuscus</nombreReceta>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente></nombreIngrediente>
                <cantidad>manzana</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente></nombreIngrediente>
                <cantidad>manzana</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones></instrucciones>
    </receta>
    <receta dificultad="fácil" tipo="asturiana">
        <nombreReceta>Fabada</nombreReceta>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>Chorizo</nombreIngrediente>
                <cantidad>100 gramos</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Chorizo</nombreIngrediente>
                <cantidad>100 gramos</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>Hay que cocer las judias y luego juntarlas con chorizo</instrucciones>
    </receta>
</recetario>
